version: 2

jobs:
  fetch:
    docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4
    steps:
      - checkout
      - restore_cache:
          key: card-images
      - run: npm install coffee-script
      - run: npm install
      - run: npm run fetch
      - save_cache:
          paths:
            - ~/resources/public/img/cards
          key: card-images

  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
      - image: mongo:3.4.4
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: lein-deps-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: lein-deps-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/netrunner-standalone.jar
          destination: uberjar

workflows:
  version: 2
  fetch-build-and-test:
    jobs:
        - fetch
        - build:
            requires:
              - fetch
