version: '3.7'

services:
  server:
    entrypoint: lein repl :headless :port 44867
    network_mode: host
    volumes:
      - "./data:/usr/src/app/data"
      - "./docs:/usr/src/app/docs"
      - "./resources:/usr/src/app/resources"
      - "./src:/usr/src/app/src"
      - "./target:/usr/src/app/target"
      - "./test:/usr/src/app/test"
    depends_on:
      - database
    build:
      context: .

  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  cljs:
    entrypoint: npm run cljs:watch
    volumes:
      - "./.shadow-cljs:/usr/src/app/.shadow-cljs"
      - "./data:/usr/src/app/data"
      - "./docs:/usr/src/app/docs"
      - "./resources:/usr/src/app/resources"
      - "./src:/usr/src/app/src"
      - "./target:/usr/src/app/target"
      - "./test:/usr/src/app/test"
      - "./shadow-cljs.edn:/usr/src/app/shadow-cljs.edn"
    ports:
      - 9630:9630
    build:
      context: .

  css:
    entrypoint: npm run css:watch
    volumes:
      - "./:/usr/src/app"
    build:
      context: .
