version: '2'
services:

  npm:
    build: .
    volumes:
      - .:/workdir
    links:
      - mongo
    command: |
      sh -c "cd /workdir
             npm install
             ./node_modules/.bin/bower --allow-root install
             OPENSHIFT_MONGODB_DB_HOST=mongo npm run fetch"

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /tmp/netrunner/mongo-data:/data/db

  lein:
    image: clojure:latest
    volumes:
      - .:/netrunner
    command: |
      sh -c "cd /netrunner
             lein cljsbuild auto dev"

  netrunner:
    image: clojure:latest
    volumes:
      - .:/netrunner
    ports:
      - 7001:7001
    environment:
      ZMQ_HOST: "*"
    command: |
      sh -c "cd /netrunner
             lein run"

  stylus:
    build: .
    volumes:
      - .:/workdir
    command: |
      sh -c "cd /workdir
             ./node_modules/.bin/stylus -w src/css -o resources/public/css/"

  coffee:
    build: .
    volumes:
      - .:/workdir
    ports:
      - 1042:1042
    links:
      - mongo
      - netrunner
    command: |
      sh -c "apt-get update && apt-get install -y libzmq3-dev
             cd /workdir
             MONGO_URL=mongodb://mongo:27017/netrunner CLOJURE_HOST=netrunner ./node_modules/.bin/coffee server.coffee"
