version: '2'
services:

  npm-install:
    image: netrunner-node
    volumes:
      - .:/netrunner
    command: |
      sh -c "npm install
             ./node_modules/.bin/bower --allow-root install"

  fetch:
    image: netrunner-node
    volumes:
      - .:/netrunner
    links:
      - mongo
    environment: 
      OPENSHIFT_MONGODB_DB_HOST: mongo 
    command: npm run fetch

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /tmp/netrunner/mongo-data:/data/db

  lein:
    image: clojure:latest
    volumes:
      - .:/netrunner
    command: |
      sh -c "cd /netrunner
             lein cljsbuild auto dev"

  netrunner:
    image: clojure:latest
    volumes:
      - .:/netrunner
    ports:
      - 7001:7001
    environment:
      ZMQ_HOST: "*"
    command: |
      sh -c "cd /netrunner
             lein run"

  stylus:
    image: netrunner-node
    volumes:
      - .:/netrunner
    command: ./node_modules/.bin/stylus -w src/css -o resources/public/css/

  coffee:
    image: netrunner-node
    volumes:
      - .:/netrunner
    ports:
      - 1042:1042
    links:
      - mongo
      - netrunner
    environment:
      MONGO_URL: mongodb://mongo:27017/netrunner
      CLOJURE_HOST: netrunner
    command: ./node_modules/.bin/coffee server.coffee
