version: '3'
services:
  jnet:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ./config.edn:/netrunner/config.edn
    ports:
      - "1042:1042"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.8
