version: '3'

services:
  jnet:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./config.edn:/netrunner/config.edn
      - resources:/netrunner/resources
    networks:
      - db_network
      - web_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.6.8
    networks:
      - db_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - resources:/opt/jinteki/netrunner/resources
    networks:
      - web_network
    ports:
      - 8080:80
    depends_on:
      - jnet

volumes:
  resources:

networks:
  db_network:
  web_network:
